2024-12-05 10:56:39,267 (76707/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 10:56:39,267 (76707/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 10:56:39,302 (76707/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect\n    attempts = conninfo_attempts(params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts\n    raise e.OperationalError(str(last_exc))\npsycopg.OperationalError: [Errno 8] nodename nor servname provided, or not known\n'
2024-12-05 10:58:38,156 (77642/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 10:58:38,163 (77642/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 10:59:53,890 (77876/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 10:59:53,890 (77876/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 10:59:53,978 (77876/MainThread) pgcli.main INFO - 0 keys loaded from agent
2024-12-05 10:59:53,978 (77876/MainThread) pgcli.main INFO - 0 key(s) loaded
2024-12-05 10:59:53,981 (77876/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/main.py", line 707, in connect\n    self.ssh_tunnel = sshtunnel.SSHTunnelForwarder(**params)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sshtunnel.py", line 966, in __init__\n    (self.ssh_password, self.ssh_pkeys) = self._consolidate_auth(\n                                          ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sshtunnel.py", line 1169, in _consolidate_auth\n    raise ValueError(\'No password or public key available!\')\nValueError: No password or public key available!\n'
2024-12-05 11:01:09,934 (78285/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:01:09,935 (78285/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:01:33,629 (78419/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:01:33,630 (78419/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:02:22,916 (78719/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:02:22,916 (78719/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:02:24,087 (78719/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "40.71.77.169", port 5432 failed: connection to server at "40.71.77.169", port 5432 failed: fe_sendauth: no password supplied\n'
2024-12-05 11:02:37,010 (78832/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:02:37,010 (78832/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:02:40,035 (78832/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/main.py", line 741, in connect\n    passwd = click.prompt(\n             ^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/click/termui.py", line 164, in prompt\n    value = prompt_func(prompt)\n            ^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
2024-12-05 11:02:50,911 (78948/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:02:50,912 (78948/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:03:50,607 (79133/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:03:50,608 (79133/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:06:52,481 (79133/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo', error: SyntaxError('syntax error at or near "\\"\nLINE 1: ...IN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo\n                                                              ^')
2024-12-05 11:06:52,484 (79133/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: ...IN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo\n                                                              ^\n'
2024-12-05 11:07:00,984 (79133/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo', error: SyntaxError('syntax error at or near "\\"\nLINE 1: ...IN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo\n                                                              ^')
2024-12-05 11:07:00,984 (79133/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: ...IN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo\n                                                              ^\n'
2024-12-05 11:07:07,494 (79133/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo', error: SyntaxError('syntax error at or near "\\"\nLINE 1: ...IN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo\n                                                              ^')
2024-12-05 11:07:07,494 (79133/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: ...IN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) \\conninfo\n                                                              ^\n'
2024-12-05 11:16:51,662 (79133/MainThread) pgcli.pgexecute ERROR - sql: 'select fdg.*, fd.*, d.*, da.* from ohzdp_workshop.final_disease_group fdg\njoin ohzdp_workshop.final_disease fd ON fd.final_disease_group_id = fdg.id\njoin ohzdp_workshop.disease d ON d.id = fd.disease_id\njoin app.disease_agent da ON da.id = d.disease_agent_idi\njoin ohzdp_workshop.disease_list ON disease_list.id = d.disease_list_id\nwhere disease_list.workshop_id=102', error: UndefinedColumn('column d.disease_agent_idi does not exist\nLINE 4: join app.disease_agent da ON da.id = d.disease_agent_idi\n                                             ^\nHINT:  Perhaps you meant to reference the column "d.disease_agent_id".')
2024-12-05 11:16:51,665 (79133/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column d.disease_agent_idi does not exist\nLINE 4: join app.disease_agent da ON da.id = d.disease_agent_idi\n                                             ^\nHINT:  Perhaps you meant to reference the column "d.disease_agent_id".\n'
2024-12-05 11:18:43,893 (81700/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:18:43,894 (81700/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:19:07,432 (81700/MainThread) pgcli.pgexecute ERROR - sql: 'select fdg.*, fd.*, d.*, da.* from ohzdp_workshop.final_disease_group fdg', error: UndefinedTable('missing FROM-clause entry for table "fd"\nLINE 1: select fdg.*, fd.*, d.*, da.* from ohzdp_workshop.final_dise...\n                      ^')
2024-12-05 11:19:07,434 (81700/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: missing FROM-clause entry for table "fd"\nLINE 1: select fdg.*, fd.*, d.*, da.* from ohzdp_workshop.final_dise...\n                      ^\n'
2024-12-05 11:22:06,647 (82577/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:22:06,647 (82577/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:23:10,129 (82846/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:23:10,130 (82846/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-12-05 11:25:21,095 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'select fdg.*, fd.*, d.*, da.* from ohzdp_workshop.final_disease_group fdg\njoin ohzdp_workshop.disease_list ON disease_list.id = d.disease_list_id\njoin ohzdp_workshop.final_disease ON final_disease.final_disease_group_id = fdg.id', error: UndefinedTable('missing FROM-clause entry for table "d"\nLINE 2: ... ohzdp_workshop.disease_list ON disease_list.id = d.disease_...\n                                                             ^')
2024-12-05 11:25:21,098 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: missing FROM-clause entry for table "d"\nLINE 2: ... ohzdp_workshop.disease_list ON disease_list.id = d.disease_...\n                                                             ^\n'
2024-12-05 11:26:08,251 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'select fdg.*, fd.*  from ohzdp_workshop.final_disease_group fdg\njoin ohzdp_workshop.final_disease fd ON final_disease.final_disease_group_id = fdg.id', error: UndefinedTable('missing FROM-clause entry for table "final_disease"\nLINE 2: join ohzdp_workshop.final_disease fd ON final_disease.final_...\n                                                ^')
2024-12-05 11:26:08,253 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: missing FROM-clause entry for table "final_disease"\nLINE 2: join ohzdp_workshop.final_disease fd ON final_disease.final_...\n                                                ^\n'
2024-12-05 11:26:26,576 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'join ohzdp_workshop.disease_list dl ON disease_list.id = fd.disease_list_id', error: SyntaxError('syntax error at or near "join"\nLINE 1: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n        ^')
2024-12-05 11:26:26,577 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "join"\nLINE 1: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n        ^\n'
2024-12-05 11:26:47,949 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'join ohzdp_workshop.disease_list dl ON disease_list.id = fd.disease_list_id\nwhere disease_list.workshop_id=102', error: SyntaxError('syntax error at or near "join"\nLINE 1: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n        ^')
2024-12-05 11:26:47,950 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "join"\nLINE 1: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n        ^\n'
2024-12-05 11:27:04,754 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'join ohzdp_workshop.disease_list dl ON disease_list.id = fd.disease_list_id\nwhere dl.workshop_id=102', error: SyntaxError('syntax error at or near "join"\nLINE 1: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n        ^')
2024-12-05 11:27:04,756 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "join"\nLINE 1: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n        ^\n'
2024-12-05 11:27:55,789 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'select fdg.*, fd.*  from ohzdp_workshop.final_disease_group fdg\njoin ohzdp_workshop.final_disease fd ON fd.final_disease_group_id = fdg.id\njoin ohzdp_workshop.disease_list dl ON disease_list.id = fd.disease_list_id\nwhere dl.workshop_id=102', error: UndefinedTable('missing FROM-clause entry for table "disease_list"\nLINE 3: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n                                               ^')
2024-12-05 11:27:55,792 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: missing FROM-clause entry for table "disease_list"\nLINE 3: join ohzdp_workshop.disease_list dl ON disease_list.id = fd....\n                                               ^\n'
2024-12-05 11:28:13,427 (82846/MainThread) pgcli.pgexecute ERROR - sql: 'select fdg.*, fd.*  from ohzdp_workshop.final_disease_group fdg\njoin ohzdp_workshop.final_disease fd ON fd.final_disease_group_id = fdg.id\njoin ohzdp_workshop.disease_list dl ON dl.id = fd.disease_list_id\nwhere dl.workshop_id=102', error: UndefinedColumn('column fd.disease_list_id does not exist\nLINE 3: join ohzdp_workshop.disease_list dl ON dl.id = fd.disease_li...\n                                                       ^\nHINT:  Perhaps you meant to reference the column "fdg.disease_list_id".')
2024-12-05 11:28:13,428 (82846/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n  File "/Users/jonpaul/.pyenv/versions/3.12.2/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column fd.disease_list_id does not exist\nLINE 3: join ohzdp_workshop.disease_list dl ON dl.id = fd.disease_li...\n                                                       ^\nHINT:  Perhaps you meant to reference the column "fdg.disease_list_id".\n'
2024-12-05 11:52:39,708 (95920/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-12-05 11:52:39,710 (95920/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
